name: Command via SSH

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run remote publish command by ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ./publish
          host: ${{ secrets.HOST }}
          username: shabinets
          password: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
